### ISSUE TITLE
Open questions: on /performance/benchmarks

### ISSUE THREAD

**Issue by qmarsun22** [bloomberg/blazingmq#103]
Regarding your
https://bloomberg.github.io/blazingmq/docs/performance/benchmarks
its a good report and thanks for publishing it and having following quesitons.

1. Did you run your scenaris with simulated network latency across 3 regions ( ASIA, Europe and America ) 
2. About Network card, Is it off the self NIC or any performance boosted network card ?

**Comment by quarter-note** [comment]
Hi @qmarsun22, to answer your questions:

> 1. Did you run your scenaris with simulated network latency across 3 regions ( ASIA, Europe and America )

No.  The maximum ping latency between the nodes was around 1.5 millisecond (this includes BlazingMQ cluster nodes as well as nodes running producer/consumer applications).  

> 2. About Network card, Is it off the self NIC or any performance boosted network card ?

Off the shelf NIC.

Out of curiosity, what interested you in BlazingMQ, and specifically in its performance numbers?

Thanks!

**Comment by qmarsun22** [comment]
>> Out of curiosity, what interested you in BlazingMQ, and specifically in its performance numbers?

Looking for  Messaging system that provide constant Latency for all messages. 
Most or all of them messaging system are  talking  about 99the percentil but in a prod envirnment even one message dealyed its a big impact for that one particular user.
