### ISSUE TITLE
why the codebase so large?

### ISSUE THREAD

**Issue by billowqiu** [bloomberg/blazingmq#110]
No third-party libraries included，blazingmq codebase use cloc output.

<img width="816" alt="image" src="https://github.com/bloomberg/blazingmq/assets/720496/9f246be4-7084-40a4-aa6b-dfac31e1377b">

**Comment by billowqiu** [comment]
@pniedzielski Thank you for your wonderful reply.

**Comment by quarter-note** [comment]
@billowqiu Please feel free to reopen if you have any additional questions.  Thanks!
