### ISSUE TITLE
Replace C-style type conversions with C++ casts

### ISSUE THREAD

**Issue by 678098** [bloomberg/blazingmq#126]
### Is there an existing proposal for this?

- [X] I have searched the existing proposals

### Is your feature request related to a problem?

There are several places where C-style conversions are used.

Search the codebase for `(double)`:

```
mwcst_printutil.cpp - 2
mwcst_statutil.cpp - 3
mwcu_printutil.t.cpp - 3
```

It's possible to find some conversions by searching for `(int)` too, but this search shows more false alarms and unrelated `(int)` usage. There are still conversions to be fixed, like:

```
int BasicTableInfoProvider::numColumns(int level) const
{
    if (level == 0) {
        return (int)d_columns.size();
    }
    else {
        return (int)d_columnGroups.size();
    }
}
```

Another possible searches: ` int(`, ` double(` (with a space in the beginning)

### Describe the solution you'd like

Use `static_cast`

Warning: there might be some auto-generated files with C-style conversions, usually with a name ending with `messages.cpp` or `messages.h`, don't need to modify it.

**Comment by mfrandev** [comment]
Hi, I would be happy to work on this issue once this comment is acknowledged.

**Comment by 678098** [comment]
Hi @mfrandev, thanks for your interest, will assign this issue to you.

**Comment by mfrandev** [comment]
Is there a reason why the .vscode/ directory has been excluded from .gitignore ? May I add this ?

**Comment by 678098** [comment]
> Is there a reason why the .vscode/ directory has been excluded from .gitignore ? May I add this ?

Yes, updating `.gitignore` would be good
