### ISSUE TITLE
How to install the libs locally after done compiling it?

### ISSUE THREAD

**Issue by faizol** [bloomberg/blazingmq#202]
### Is there an existing proposal for this?

- [X] I have searched the existing proposals

### Is your feature request related to a problem?

Successfully compiled the library, and now trying to compile the tutorial source code. 

### Describe the solution you'd like

I successfully compiled the library using the supplied sh script. Now how can I install the libraries in usual places (/usr/local/*) for local development?

**Comment by pniedzielski** [comment]
Hi @faizol.  Thanks for trying BlazingMQ!  If you're using the `build-ubuntu.sh` script, you can set the `DIR_INSTALL` environment variable to be the path you want the installed artifacts to end up:

    DIR_INSTALL=/usr/local ./bin/build-ubuntu.sh
    
Let me know if you have any issues with this.

**Comment by faizol** [comment]
Thank you, that solved it.
