### ISSUE TITLE
`mwcc_orderedhashmap` invokes undefined behavior in `bdlma_pool` for more than 1359964751 buckets/insertions

### ISSUE THREAD

**Issue by pniedzielski** [bloomberg/blazingmq#247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Discovered in #245, compiler warns of a `size_t` to `int` unsigned-to-signed integral conversion within `mwcc_orderedhashmap`:

    /home/runner/work/blazingmq/blazingmq/src/groups/mwc/mwcc/mwcc_orderedhashmap.h:1197:58: warning: conversion from ‘size_t’ {aka ‘long unsigned int’} to ‘int’ may change value [-Wconversion]
     1197 |             d_nodePool.reserveCapacity(d_bucketArraySize - d_numElements);
          |                                        ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~

Here `d_bucketArraySize` and `d_numElements` are of type `size_t` and `d_nodePool.reserveCapacity()` from `bdlma_pool` expects an `int`, with the precondition that that integer must be nonnegative.  A similar call is found elsewhere in the file, reserving directly `d_bucketArraySize`.

`d_bucketArraySize` is set by calling `OrderedHashMap_ImpDetails::nextPrime`, which selects from a list of geometrically growing prime numbers.  The largest of these is `2719929503u`, which is not representable within a 32-bit `int`.  So, when the implicit conversion from `d_bucketArraySize` from `size_t` to `int` takes place, we get implementation defined behavior pre-C++20, and modular behavior with C++20 or later.  The later certainly results in a negative integer, and the former does on many implementations.  This negative number is passed to `reserveCapacity`, violating its contract.

### Expected Behavior

No undefined behavior :)

### Steps To Reproduce

If it is possible to insert enough that there are more than 1359964751 buckets, we should get an assertion failure from BDE.

### BlazingMQ Version

HEAD

### Anything else?

The simple fix for this is to remove `2719929503u` from `nextPrime`.  Once `nextPrime` reaches the largest prime it knows about, it returns 0 as an error, which MWC handles by throwing a `runtime_error`---well-defined behavior.

**Comment by pniedzielski** [comment]
@melvinhe --- tracking the issue discovered in #245 here.

**Comment by melvinhe** [comment]
> @melvinhe --- tracking the issue discovered in #245 here.

Sounds good, will now be attempting to fix this bug: updating `nextPrime` and subsequently running a few commit checks through the CI with a `size_t` to `int` casting approach to maintain consistency with `bldma_pool` [docs](https://bloomberg.github.io/bde-resources/doxygen/bde_api_prod/classbdlma_1_1Pool.html#a2a8ab64992212d4f3abde7f47f2a5799).

**Comment by pniedzielski** [comment]
Sounds good!

**Comment by pniedzielski** [comment]
Fixed in #248
