### ISSUE TITLE
Can't download bmqbrkr image from docker

### ISSUE THREAD

**Issue by robotnoises** [bloomberg/blazingmq#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm attempting to start the single-node test project but when I run `docker-compose` I get the following:

```
docker compose -f docker/single-node/docker-compose.yaml up --build -d
[+] Running 0/1
 ⠿ bmqtool Error                                                                                                                                
Error response from daemon: pull access denied for bmqbrkr, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

### Expected Behavior

I expected the docker container(s) to start up.

### Steps To Reproduce

```
> git clone git@github.com:bloomberg/blazingmq.git
> cd blazingmq
> docker login
> docker compose -f docker/single-node/docker-compose.yaml up --build -d
```

### BlazingMQ Version

0.0.0

### Anything else?

I checked out docker hub but I don't see the image `bmqbrkr` anywhere.

**Comment by jll63** [comment]
The example does not download a `bmqbrkr` image - only [a stock ubuntu image](https://github.com/bloomberg/blazingmq/blob/main/docker/Dockerfile#L1). It does, though, create a local `bmqbrkr` image.

Please try again, using the exact command from the documentation:

```
docker-compose -f docker/single-node/docker-compose.yaml up --detach
```

**Comment by robotnoises** [comment]
That worked, thanks!
