### ISSUE TITLE
Docker images missing platform for use on MacOS

### ISSUE THREAD

**Issue by Cartroo** [bloomberg/blazingmq#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Following the instructions in the [_Blazing MQ In Action_](https://bloomberg.github.io/blazingmq/docs/getting_started/blazingmq_in_action/) article doesn't work on MacOS as it fails with the following error:

```
36.14 + build
36.14 + build_bde
36.14 /workspace/srcs/bde /workspace
36.14 + pushd srcs/bde
36.14 + bbs_build configure
36.17 rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2
```

### Expected Behavior

The docker images are successfully built.

### Steps To Reproduce

1. On MacOS (Sonoma 14.5) on Apple M2 silicon, execute the first `docker compose` command.

### BlazingMQ Version

0.92.5

### Anything else?

The following patch seems to fix it for the single node case, I haven't yet tried anything else.

```
diff --git a/docker/single-node/docker-compose.yaml b/docker/single-node/docker-compose.yaml
index 5039bdb..c7ba220 100644
--- a/docker/single-node/docker-compose.yaml
+++ b/docker/single-node/docker-compose.yaml
@@ -1,5 +1,6 @@
 services:
   bmqbrkr:
+    platform: linux/amd64
     image: bmqbrkr:latest
     build:
       context: ../..
@@ -10,6 +11,7 @@ services:
     command: "/usr/local/bin/bmqbrkr /etc/local/bmq"

   bmqtool:
+    platform: linux/amd64
     image: bmqbrkr:latest
     build:
       context: ../..
```

**Comment by 678098** [comment]
Hi @Cartroo, thanks for reporting this issue, we fixed it in the linked PR.

**Comment by Cartroo** [comment]
Thanks! I'm not enough of a Docker expert to be certain whether there were any negative implications of applying it myself.
