### ISSUE TITLE
Remove unused header mwcsys_executil.h from the codebase

### ISSUE THREAD

**Issue by 678098** [bloomberg/blazingmq#36]
### Is there an existing proposal for this?

- [X] I have searched the existing proposals

### Is your feature request related to a problem?

If you search for `ExecUtil` usage, you can find some files with unused `#include <mwcsys_executil.h>`: 
https://github.com/search?q=repo%3Abloomberg%2Fblazingmq%20ExecUtil&type=code

### Describe the solution you'd like

Will be good to remove these unused includes where possible, while keeping files `mwcsys_executil.h`, `mwcsys_executil.cpp`, `mwcsys_executil.t.cpp`. These files might be used by existing library's clients.

**Comment by parkma99** [comment]
I would like to take it.

**Comment by SaketKaswa20** [comment]
I would love to take a try on it.

**Comment by quarter-note** [comment]
Hi @SaketKaswa20, since @parkma99 expressed interest first, I think it would be fair for them to take a shot at it :).  @parkma99 Please let us know if you'd like to proceed.

**Comment by parkma99** [comment]
Hello @quarter-note @SaketKaswa20 , #45  My machine is M2 Mac,  I find it is hard to build this project,so I give up this issue,

**Comment by SaketKaswa20** [comment]
I can surely try, please assign me.

**Comment by 678098** [comment]
> I can surely try, please assign me.

Assigned, feel free to ask if you have any questions

**Comment by SaketKaswa20** [comment]
Hey, I searched for `ExecUtil` and found some files. Read the code where `#include<mwcsys_executil.h>`, but I am a bit confused on how to find which is useful or not. It would be great, if you can guide me or refer some documentation. I am eager to solve this issue.

**Comment by 678098** [comment]
@SaketKaswa20 
There are 2 base files which are interesting for this task:
https://github.com/bloomberg/blazingmq/blob/main/src/groups/mwc/mwcsys/mwcsys_executil.h
https://github.com/bloomberg/blazingmq/blob/main/src/groups/mwc/mwcsys/mwcsys_executil.cpp

In general, when you want to remove some includes, you need to address several things:
- What entities (classes, functions, variables) declared/defined in interface. From the header at the top you can see that only `struct ExecUtil` declared, so, to the question of "is it useful or not" - you can check if this `ExecUtil` used.
- What includes are added recursively and will be lost. Here you can see the `bsl_string.h` include only. Simply trying to build will show if some includes were lost, but I don't think there will be a problem here.
- What other side-effects .cpp/.h files have. For example, in some files static memory might be initialized to store some objects. Removing includes might exclude object files based on these sources from linking to the final app/lib and break something. I think there are no problems here.

To move things forward you can start with a simple PR, we have a CI with unit tests which will help to check build
