### ISSUE TITLE
Advantages over zmq ?

### ISSUE THREAD

**Issue by fire17** [bloomberg/blazingmq#43]
Hi there, first time hearing about this project,
I am used to zmq and zeroless to either send heavy data msgs or bulk async request, and I have easy python wrappers to interface with

Can you please explain how is is blazingmq better, in terms of benchmarks performance, features, and other metrics ?

Excited to experiment with it
Thanks a lot and all the best!

**Comment by fire17** [comment]
Awesome @jll63 ! 
Good luck and thanks for going open source it sounds really awesome :D

As i understand currently,  The main advantage is the robustness of the system, and ease of scaleup.
I would still like to know how's your performance, would love to know the latency of a healthy (local) system, how many msgs can be sent / recieved a second? how much performance in terms of ram and cpu does it consume during idle while working? and if you think it can be applied to Realtime, Big Volume, Datadriven, Multi-Service Systems?
From the name it seems so haha

I'm managing own microservice solution, and using varius communication adapters under thehood (zmq, fastapi, etc)
for now zmq gave me the best realtime performance, but i'm happy to try other options.
Also, if i got it right, once it is set up, it should be easy to add a node to the cluster. But also wondering about the small scale, can this be run in a dev environment locally to test out first? how easy it is to setup one node and connect clients to it? And lastly... do you provide python wrappings? so it can be accessed by my systems

Thanks for responding! Have a good one & all the best!

**Comment by quarter-note** [comment]
Hi @fire17 Let me try to answer some of your questions.

> I would still like to know how's your performance, would love to know the latency of a healthy (local) system.

Performance of a clustered setup can be found [here](https://bloomberg.github.io/blazingmq/docs/performance/benchmarks/).
We have benchmarked local setup as well (1-node BlazingMQ cluster, with producers and consumers running locally as well).  For *in-memory* queues (no persistence), BlazingMQ can achieve 300,000+ msgs/second throughput for one queue.  For *persistent* queue, the number is around 220,000 msgs/second for one queue.  In both cases, producer was posting messages in a batch, with each message of size 1KB with no compression.  The latency can vary anywhere from double-digit microseconds to ~1 millisecond, depending on the batch size, producer's publishing pattern (bursty vs smooth), etc.  Generally speaking, benchmarking can be very tricky, and numbers can vary based on the hardware, broker configuration, placement of nodes, etc.

> can this be run in a dev environment locally to test out first? 

Yes!  Please see [this](https://bloomberg.github.io/blazingmq/docs/getting_started/blazingmq_in_action/) article.

> how easy it is to setup one node and connect clients to it?

Very easy!  [This](https://bloomberg.github.io/blazingmq/installation) article goes over configuration and deployment of BlazingMQ.  The article focuses on a clustered deployment, and we are happy to work with you to figure out a good 1-node setup as well.

> do you provide python wrappings?
Python SDK is coming soon (in a couple of months or so).  Please also see [this]https://github.com/bloomberg/blazingmq/discussions/69#discussioncomment-6642466) note about it.

**Comment by quarter-note** [comment]
Also keep in mind that the numbers for local setup that I provided above are for priority queue, not for broadcast queue.  Broadcast queue has no persistence, and matches ZeroMQ closest.  So BlazingMQ's throughput for broadcast queue in a local setup will be significantly higher, and latency will be lower than the priority queue.

**Comment by jcalahor** [comment]
zero mq is nothing more than sockets with esteroids
