### ISSUE TITLE
Add shell linting on GitHub actions

### ISSUE THREAD

**Issue by pniedzielski** [bloomberg/blazingmq#62]
### Is there an existing proposal for this?

- [X] I have searched the existing proposals

### Is your feature request related to a problem?

Currently our GitHub actions lack a linting step for shell scripts.  Doing so might have been able to catch some of the comments of #34 and #54 before review.

### Describe the solution you'd like

Proposed solution is to add a step similar to the `clang-format` step we already run on C++ code.

**Comment by Simon-Sandrew** [comment]
I'd like to take a stab at this

**Comment by pniedzielski** [comment]
Fixed with commit 1ee55e5.
