### ISSUE TITLE
Fix: add checks to pointer arguments in `m_bmqtool_inpututil`

### ISSUE THREAD

**Issue by 678098** [bloomberg/blazingmq#81]
### Is there an existing proposal for this?

- [X] I have searched the existing proposals

### Is your feature request related to a problem?

Files: `m_bmqtool_inpututil.h` and `m_bmqtool_inpututil.cpp`

There are functions with arguments passed as a pointer, with assumption that these pointer values are not null.

Example:

https://github.com/bloomberg/blazingmq/blob/9b692fe25f74543e954a27e30b6b15b0ae057c8d/src/applications/bmqtool/m_bmqtool_inpututil.cpp#L50-L53

### Describe the solution you'd like

Add checks to pointer arguments to functions in `m_bmqtool_inpututil`.

Example:

https://github.com/bloomberg/blazingmq/blob/9b692fe25f74543e954a27e30b6b15b0ae057c8d/src/groups/mqb/mqbmock/mqbmock_cluster.cpp#L380-L384

**Comment by Dyex719** [comment]
Seems like a simple fix. Can I take this up?

**Comment by 678098** [comment]
Hi @Dyex719 ! Thanks for your interest, you can proceed with this.
Just a gentle reminder, we have a DCO check for all commits in PR, the simple instruction is here: https://github.com/bloomberg/blazingmq/blob/main/CONTRIBUTING.md#contribution-licensing

**Comment by 678098** [comment]
Hi @Dyex719! Do you plan to solve this issue?

**Comment by Dyex719** [comment]
Yes. Do I need to follow these steps to build blazingmq locally? https://github.com/bloomberg/blazingmq#building

**Comment by Dyex719** [comment]
How can I test these changes?

**Comment by 678098** [comment]
> How can I test these changes?

The PR is good, merged.

Thank you @Dyex719 for your contribution!
